### ISSUE TITLE
ActionLinkFixture.click points at a wrong location

### ISSUE THREAD

**Issue by damien-urruty-sonarsource** [JetBrains/intellij-ui-test-robot#19]
Hello,

I didn't find a better place to report this issue since I don't know where the sources of the remote-fixtures lib are hosted (maybe privately?). I am using 1.1.18.

I noticed an issue with ActionLinkFixture.click(). When looking at the test running, the click was done at a wrong position. When decompiling the code in IntelliJ, we have:

    override fun click() {
        step("..click") {
            runJs("""
                const offset = component.height / 2
                robot.click(component, new Point(offset, offset), MouseButton.LEFT_BUTTON, 1)
            """);
        }
    }

My use case is that the ActionLink is inside a HorizontalLayout, so it fills the whole height, and its height is bigger than the width. The same `offset` being used for x and y in the point, it goes too far at the right of the component. 

I worked around the issue by not using ActionLinkFixture but directly JLabelFixture.click(), which works correctly.

**Comment by nizienko** [comment]
Hello, 
this is the right place to report. Indeed the remote-fixtures are in private repository now. But we are working on moving the library here. Once we did it we publish updated version which I believe already has a fix for the issue.

**Comment by nizienko** [comment]
Hello, we moved `remote-fixtures` to this github project. The issue must be fixed in the `0.11.3` version

**Comment by henryju** [comment]
Hi,

I still see this issue with 0.11.4. On CLion 2019.3, I can't manage to click on the `Open` link on the welcome frame. 
`actionLink(ActionLinkFixture.byText("Open")).click()`
This is because the robot tries to click on the center of the component, that is not clickable:
![image](https://user-images.githubusercontent.com/281596/119377790-d008a380-bcbd-11eb-9244-ea03c955ec92.png)

**Comment by henryju** [comment]
Workaround: `actionLink(ActionLinkFixture.byText("Open")).click(Point(10, 10))`

**Comment by nizienko** [comment]
Thanks! Another workaround could be to click on text:
`welcomeFixture.findText("Open").click()`
